# Generated by Django 4.1.6 on 2023-02-22 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scope', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Info',
        ),
    ]
