# Generated by Django 4.1.6 on 2023-02-23 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scope', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('dob', models.DateField(max_length=8)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=12)),
                ('country', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=25)),
                ('city', models.CharField(max_length=15)),
                ('hobbies', models.CharField(max_length=50)),
                ('img', models.ImageField(upload_to='register')),
            ],
        ),
    ]
